alias webup='sudo python -m http.server 80'
alias gobusterz='gobuster dir -w /usr/share/wordlists/dirbuster/directory-list-lowercase-2.3-medium.txt -u $1'
alias nmapz='nmap -p- --min-rate 10000 $1'
alias c='clear'
alias johnz='john  --wordlist=/usr/share/wordlists/rockyou.txt $1'
alias hostz='sudo nano /etc/hosts'
alias ncz='nc -nlvp 1337'
alias aliasz='sudo nano ~/.bash_aliases'
alias gh='history|grep'
alias upshell='echo -e "script /dev/null -c bash\n^z\nstty raw -echo; fg\nreset\nxterm "'
alias lsz='ls -alps'
alias hw='cd ~/code/cs24'
